"""Hermetic compiler probes used instead of ./configure's cached answers."""

load("@rules_cc_autoconf//autoconf:checks.bzl", "checks", "macros")

_POLICY = [
    checks.AC_DEFINE("CONFIG_BUILD_FINDFS"),
    checks.AC_DEFINE("CONFIG_MMP"),
    checks.AC_DEFINE("CONFIG_TDB"),
    checks.AC_DEFINE("CONFIG_TESTIO_DEBUG"),
    checks.AC_DEFINE("ENABLE_BMAP_STATS"),
    checks.AC_DEFINE("ENABLE_NLS"),
    checks.AC_DEFINE("USE_UUIDD"),
    checks.AC_DEFINE("STDC_HEADERS"),
    checks.AC_DEFINE("CONFIG_DISABLE_LIBARCHIVE"),
    checks.AC_DEFINE("HAVE_EXT2_IOCTLS"),
    checks.AC_DEFINE("HAVE_PTHREAD"),
    checks.AC_DEFINE("PACKAGE", '"e2fsprogs"'),
    checks.AC_DEFINE("VERSION", '"0.14.1"'),
    checks.AC_DEFINE("PACKAGE_NAME", '""'),
    checks.AC_DEFINE("PACKAGE_TARNAME", '""'),
    checks.AC_DEFINE("PACKAGE_VERSION", '""'),
    checks.AC_DEFINE("PACKAGE_STRING", '""'),
    checks.AC_DEFINE("PACKAGE_BUGREPORT", '""'),
    checks.AC_DEFINE("PACKAGE_URL", '""'),
    checks.AC_DEFINE("_ALL_SOURCE"),
    checks.AC_DEFINE("_DARWIN_C_SOURCE"),
    checks.AC_DEFINE("__EXTENSIONS__"),
    checks.AC_DEFINE("_GNU_SOURCE"),
    checks.AC_DEFINE("_HPUX_ALT_XOPEN_SOCKET_API"),
    checks.AC_DEFINE("_NETBSD_SOURCE"),
    checks.AC_DEFINE("_OPENBSD_SOURCE"),
    checks.AC_DEFINE("_POSIX_PTHREAD_SEMANTICS"),
    checks.AC_DEFINE("_TANDEM_SOURCE"),
    checks.AC_DEFINE("__STDC_WANT_IEC_60559_ATTRIBS_EXT__"),
    checks.AC_DEFINE("__STDC_WANT_IEC_60559_BFP_EXT__"),
    checks.AC_DEFINE("__STDC_WANT_IEC_60559_DFP_EXT__"),
    checks.AC_DEFINE("__STDC_WANT_IEC_60559_EXT__"),
    checks.AC_DEFINE("__STDC_WANT_IEC_60559_FUNCS_EXT__"),
    checks.AC_DEFINE("__STDC_WANT_IEC_60559_TYPES_EXT__"),
    checks.AC_DEFINE("__STDC_WANT_LIB_EXT2__"),
    checks.AC_DEFINE("__STDC_WANT_MATH_SPEC_FUNCS__"),
]

_HEADERS = [
    "dirent.h",
    "errno.h",
    "execinfo.h",
    "getopt.h",
    "inttypes.h",
    "linux/falloc.h",
    "linux/fd.h",
    "linux/fsmap.h",
    "linux/fsverity.h",
    "linux/loop.h",
    "linux/major.h",
    "linux/types.h",
    "malloc.h",
    "mntent.h",
    "net/if.h",
    "netinet/in.h",
    "paths.h",
    "pthread.h",
    "semaphore.h",
    "setjmp.h",
    "signal.h",
    "stdarg.h",
    "stdint.h",
    "stdio.h",
    "stdlib.h",
    "string.h",
    "strings.h",
    "sys/file.h",
    "sys/ioctl.h",
    "sys/mman.h",
    "sys/mount.h",
    "sys/prctl.h",
    "sys/random.h",
    "sys/resource.h",
    "sys/select.h",
    "sys/socket.h",
    "sys/stat.h",
    "sys/syscall.h",
    "sys/sysmacros.h",
    "sys/time.h",
    "sys/types.h",
    "sys/un.h",
    "sys/wait.h",
    "sys/xattr.h",
    "termio.h",
    "termios.h",
    "unistd.h",
    "utime.h",
    "wchar.h",
]

_FUNCTIONS = [
    "backtrace",
    "dcgettext",
    "dlopen",
    "fallocate",
    "fallocate64",
    "fchown",
    "fcntl",
    "fdatasync",
    "fstat64",
    "fsync",
    "ftruncate64",
    "futimes",
    "getcwd",
    "getdtablesize",
    "getentropy",
    "gethostname",
    "getpwuid_r",
    "getrandom",
    "getrlimit",
    "getrusage",
    "gettext",
    "gettid",
    "jrand48",
    "llistxattr",
    "lseek64",
    "mallinfo",
    "mallinfo2",
    "mbstowcs",
    "memalign",
    "mempcpy",
    "mmap",
    "msync",
    "nanosleep",
    "open64",
    "pathconf",
    "posix_fadvise",
    "posix_fadvise64",
    "posix_memalign",
    "prctl",
    "pread",
    "pread64",
    "pwrite",
    "pwrite64",
    "pthread_setname_np",
    "qsort_r",
    "secure_getenv",
    "setmntent",
    "setresgid",
    "setresuid",
    "snprintf",
    "srandom",
    "stpcpy",
    "strcasecmp",
    "strdup",
    "strnlen",
    "strptime",
    "strtoull",
    "sync_file_range",
    "sysconf",
    "usleep",
    "utime",
    "utimes",
    "valloc",
    "vprintf",
]

_SIZEOF = [
    ("short", "SIZEOF_SHORT"),
    ("int", "SIZEOF_INT"),
    ("long", "SIZEOF_LONG"),
    ("long long", "SIZEOF_LONG_LONG"),
    ("off_t", "SIZEOF_OFF_T"),
    ("time_t", "SIZEOF_TIME_T"),
    ("void *", "SIZEOF_VOID_P"),
]

def _size_checks():
    return [
        checks.AC_CHECK_SIZEOF(
            type_name,
            define = define,
            subst = define,
            includes = ["#include <sys/types.h>", "#include <time.h>"] if type_name in ["off_t", "time_t"] else None,
        )
        for type_name, define in _SIZEOF
    ]

def _custom_checks():
    return [
        checks.AC_CHECK_MEMBER("struct dirent.d_reclen", define = "HAVE_RECLEN_DIRENT", includes = ["#include <dirent.h>"]),
        checks.AC_CHECK_MEMBER("struct stat.st_atim", define = "HAVE_STRUCT_STAT_ST_ATIM", includes = ["#include <sys/stat.h>"]),
        checks.AC_CHECK_MEMBER("struct sockaddr.sa_len", define = "HAVE_SA_LEN", includes = ["#include <sys/types.h>", "#include <sys/socket.h>"]),
        checks.AC_CHECK_TYPE("ssize_t", define = "HAVE_TYPE_SSIZE_T", includes = ["#include <sys/types.h>"]),
        checks.AC_CHECK_TYPE("intptr_t", define = "HAVE_INTPTR_T", includes = ["#include <stdint.h>"]),
        checks.AC_CHECK_DECL("llseek", includes = ["#include <unistd.h>"]),
        checks.AC_DEFINE("HAVE_LLSEEK_PROTOTYPE", condition = "ac_cv_have_decl_llseek", if_true = 1, if_false = None),
        checks.AC_CHECK_DECL("lseek64", includes = ["#define _LARGEFILE_SOURCE", "#define _LARGEFILE64_SOURCE", "#include <unistd.h>"]),
        checks.AC_DEFINE("HAVE_LSEEK64_PROTOTYPE", condition = "ac_cv_have_decl_lseek64", if_true = 1, if_false = None),
        checks.AC_CHECK_DECL("fsmap_sizeof", includes = ["#include <linux/fsmap.h>"]),
        checks.AC_DEFINE("HAVE_FSMAP_SIZEOF", condition = "ac_cv_have_decl_fsmap_sizeof", if_true = 1, if_false = None),
        checks.AC_CHECK_DECL("FS_IOC_READ_VERITY_METADATA", includes = ["#include <linux/fsverity.h>"]),
        checks.AC_DEFINE("HAVE_FS_IOC_READ_VERITY_METADATA", condition = "ac_cv_have_decl_fs_ioc_read_verity_metadata", if_true = 1, if_false = None),
        checks.AC_TRY_COMPILE(
            name = "e2fsprogs_cv_struct_st_flags",
            define = "HAVE_STAT_FLAGS",
            code = "struct stat stat; stat.st_flags = 0;",
            includes = ["#include <sys/stat.h>"],
        ),
        checks.AC_TRY_COMPILE(
            name = "e2fsprogs_cv_gnu_qsort_r",
            define = "HAVE_GNU_QSORT_R",
            code = "int (*fn)(const void *, const void *, void *) = 0; qsort_r(0, 0, 0, fn, 0);",
            includes = ["#include <stdlib.h>"],
        ),
        checks.AC_TRY_COMPILE(
            name = "e2fsprogs_cv_mount_flags",
            define = "HAVE_MOUNT_NODEV",
            code = "int x = MS_NODEV; return x;",
            includes = ["#include <sys/mount.h>"],
        ),
        checks.AC_TRY_COMPILE(
            name = "e2fsprogs_cv_mount_nosuid",
            define = "HAVE_MOUNT_NOSUID",
            code = "int x = MS_NOSUID; return x;",
            includes = ["#include <sys/mount.h>"],
        ),
        checks.AC_TRY_LINK(
            name = "e2fsprogs_cv_clock_monotonic",
            define = "HAVE_CLOCK_MONOTONIC",
            code = "#define _GNU_SOURCE\n#include <time.h>\nint main(void) { struct timespec nuts; return clock_gettime(CLOCK_MONOTONIC, &nuts); }",
        ),
        checks.AC_TRY_LINK(
            name = "e2fsprogs_cv_pr_set_io_flusher",
            define = "HAVE_PR_SET_IO_FLUSHER",
            code = "#define _GNU_SOURCE\n#include <sys/prctl.h>\nint main(void) { return prctl(PR_SET_IO_FLUSHER, 0, 0, 0, 0); }",
        ),
        checks.AC_TRY_COMPILE(
            name = "e2fsprogs_cv_pthread_prio_inherit",
            define = "HAVE_PTHREAD_PRIO_INHERIT",
            code = "int x = PTHREAD_PRIO_INHERIT; return x;",
            includes = ["#include <pthread.h>"],
        ),
    ]

def e2fs_checks():
    return _POLICY + macros.AC_CHECK_HEADERS(_HEADERS) + macros.AC_CHECK_FUNCS(_FUNCTIONS) + _size_checks() + _custom_checks()
