# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

""" TODO: Write docstrings
"""

load(":common/attrs.bzl", _COMMON_RULES_ATTRS = "COMMON_RULES_ATTRS")
load(":common/qnx_image.bzl", "gen_image_definition")

COMMON_RULES_ATTRS = _COMMON_RULES_ATTRS

def prep_output(ctx):
    """
    Determines and declares the output file for the QNX image build action.

    This function resolves the output filename based on rule attributes. If
    `ctx.attr.out` is explicitly provided, it is used directly; otherwise, the
    filename is derived from the rule name and the specified extension. The
    function validates that the resulting filename does not contain any path
    components, ensuring it represents a single artifact in the current package.
    It then declares the output file via `ctx.actions.declare_file`.

    Args:
        ctx: The rule context (`RuleContext`) provided by Bazel. It is expected
            to expose the following attributes:
            - ctx.attr.out: Optional explicit output filename.
            - ctx.attr.name: Name of the rule, used as a fallback prefix.
            - ctx.attr.extension: File extension used when `out` is not provided.

    Returns:
        File: A declared output `File` object representing the generated QNX
        image artifact.

    Raises:
        Fail: If the resolved output name contains path separators (i.e., is not
        a simple filename).
    """
    out_name = ctx.attr.out if ctx.attr.out else "{}.{}".format(ctx.attr.name, ctx.attr.extension)
    if "/" in out_name:
        fail("qnx_ifs.out must be a filename without path components, got: {}".format(out_name))

    return ctx.actions.declare_file(out_name)

def prep_inputs(ctx):
    """
    Prepares and aggregates input files required for QNX image generation.

    This function invokes `gen_image_definition` to resolve the QNX image
    definition artifacts, including the main build file, any included build
    files, and filesystem contents. It then appends these artifacts to the
    `inputs` collection, which is intended to be consumed by a downstream
    Bazel action. Additionally, it returns the path to the main build file,
    which typically serves as the entry point for the image generation process.

    Args:
        ctx: The rule context (`RuleContext`) provided by Bazel. It is expected
            to expose the following attributes:
            - ctx.attr.all_files: Combined set of source inputs (e.g., DUI,
              rules_pkg outputs, and regular files).
            - ctx.file.build_file: Optional main build file.
            - ctx.files.extra_build_files: Additional build files to be included.

    Returns:
        A tuple containing:
            - main_build_file.path (str): Filesystem path to the main QNX build
              file used as the entry point.
            - inputs (list[File]): List of input `File` objects including the
              main build file, additional build files, and filesystem contents.
    """
    main_build_file, build_files, fs_contents = gen_image_definition(
        ctx,
        srcs = ctx.attr.srcs,
        extra_build_file = ctx.file.build_file,
        extra_build_files = ctx.files.extra_build_files,
    )

    inputs = []
    inputs.append(main_build_file)
    inputs.extend(build_files)
    inputs.extend(fs_contents)

    return main_build_file.path, inputs

def gen_image(ctx, inputs, outputs, arguments, image_tc_type):
    """
    Executes an image generation action by invoking a selected tool.

    This function registers a `ctx.actions.run` action that uses the specified
    executable and environment from `tool_info` to transform `inputs` into
    `outputs`. It then returns a `DefaultInfo` provider exposing the generated
    output files.

    Args:
        ctx: The rule context (`RuleContext`) provided by Bazel. Used to declare
            and register build actions.
        inputs: A sequence or depset of input `File` objects required by the
            action.
        outputs: A list of output `File` objects that will be generated by the
            action.
        arguments: A list of command-line arguments passed to the executable.
        image_tc_type: .

    Returns:
        A list containing a single `DefaultInfo` provider, where `files` is a
        depset of the generated output files.
    """
    tool_info = ctx.toolchains[image_tc_type].imagefs_toolchain_info
    ctx.actions.run(
        outputs = outputs,
        inputs = inputs,
        arguments = arguments,
        executable = tool_info.executable,
        env = tool_info.env,
        tools = tool_info.tools,
    )
    return [DefaultInfo(files = depset(outputs))]
